/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

void ADC1_2_IRQHandler() {
}


int main(void) {
	//Enable Clock for GPIO
	
	//Enable Clock for ADC
	
	//Select ADC clock as System clock
	

	//Change Pin Mode to Analog
	

	//Change Pin Pull/Down to no pull-up no pull-down

	//Change Regular channel sequence length to 1 conversion


	//Add to channel to first sequence
	

	//Disable Deep-power-down for ADC
	

	//Enable ADC Voltage regulator
	

	//Configure for Single conversion mode
	

	//Enable ADC
	

	//Wait ADC is enabled
	

	//Enable interrupt for end of regular conversion
	


	//Start regular conversion of ADC

	//Write program according to problem description
	while(1){

	}
}
