/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

void LPUART1_IRQHandler() {
}

int main(void) {
	//Enable Clock for Power Interface

	//Change the regulator mode to Low-power mode

	//Make VDDIO2 valid

	//Change the clock source of Low-power UART to SYSCLK

	//Enable Clock for Low-power UART

	//Enable Clock for GPIO

	//Change the functionality of the pin

	//Change LPUART baud rate (BRR) for 9600 Baud rate

	//Enable FIFO mode for UART

	//Enable Transmitter and Receiver for UART
	
	//Enable Interrupt and LPUART

	while(1){
	}
}
