/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "func.h"

bool_t
xdr_S (XDR *xdrs, S *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->c, ~0))
		 return FALSE;
	return TRUE;
}
