/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

typedef struct {
	volatile uint8_t MODER[4];
	volatile uint8_t OTYPER[4];
	volatile uint8_t OSPEEDR[4];
	volatile uint8_t PUPDR[4];
	volatile uint8_t IDR[4];
	volatile uint8_t ODR[4];
	volatile uint8_t BSRR[4];
	volatile uint8_t LCKR[4];
	volatile uint8_t AFR[8];
	volatile uint8_t BRR[4];
	uint8_t RESERVED[4];
	volatile uint8_t SECCFGR[4];
} GPIO_TypeDef;

uint32_t wait_milisecond = 1000;
uint32_t wait_counter = 0;

#define RCC_AHB2ENR *((volatile uint32_t *) (0x40021000 + 0x4C))

#define GPIOA	((GPIO_TypeDef *) 0x42020000)

int main(void) {
	RCC_AHB2ENR |= 0x01 << 0;

	GPIOA->MODER[2] &= ~(0x03 << (1 * 2));
	GPIOA->MODER[2] |= (0x01 << (1 * 2));

	while(1) {
		int index;

		GPIOA->ODR[1] |= (0x01 << 1);

		for(index=0;index<wait_milisecond*333;index++);

		__asm volatile("LDR R12, [%0]" : :"r"(&wait_counter));
		__asm volatile("ADD R12, 1");
		__asm volatile("STR R12, [%0]" : :"r"(&wait_counter));

		GPIOA->ODR[1] &= ~(0x01 << 1);

		for(index=0;index<wait_milisecond*333;index++);

		__asm volatile("MOV R12, %0" : :"r"(wait_counter));
		__asm volatile("ADDS R12, #0x01");
		__asm volatile("MOV %0, R12" : "=r"(wait_counter));
	}
}
