/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FUNC_H_RPCGEN
#define _FUNC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct S {
	int a;
	int b;
	char *c;
};
typedef struct S S;

#define FUNC_PROG 0x12345678
#define FUNC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define FUNC 1
extern  char ** func_1(S *, CLIENT *);
extern  char ** func_1_svc(S *, struct svc_req *);
extern int func_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FUNC 1
extern  char ** func_1();
extern  char ** func_1_svc();
extern int func_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_S (XDR *, S*);

#else /* K&R C */
extern bool_t xdr_S ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FUNC_H_RPCGEN */
